apiVersion: v1
kind: Service
metadata:
  name: config-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path:   "/actuator/prometheus"
    prometheus.io/port:   "9090"
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer  