apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path:   "/actuator/prometheus"
    prometheus.io/port:   "8093"
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8093
  type: ClusterIP