apiVersion: v1
kind: Service
metadata:
  name: ter-logement-service
  labels:
    app: ter-logement
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    app: ter-logement