apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path:   "/actuator/prometheus"
    prometheus.io/port:   "8761"
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: eureka-server