{
 "title": "DashboardMicroserviceFinal",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SECTION 1 – Cluster & Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation CPU",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n",
     "legendFormat": "Libre"
    },
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))\n",
     "legendFormat": "Utilisé"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/data\", fstype!=\"tmpfs\"} - node_filesystem_free_bytes{mountpoint=\"/data\", fstype!=\"tmpfs\"})\n/\nnode_filesystem_size_bytes{mountpoint=\"/data\", fstype!=\"tmpfs\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occupation disque",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(node_filesystem_free_bytes{fstype!=\"tmpfs\", mountpoint!~\"/run.*\"}) \n/ sum(node_filesystem_size_bytes{fstype!=\"tmpfs\", mountpoint!~\"/run.*\"})\n",
     "legendFormat": "Libre"
    },
    {
     "expr": "100 * (\n  sum(node_filesystem_size_bytes{fstype!=\"tmpfs\", mountpoint!~\"/run.*\"}) \n  - sum(node_filesystem_free_bytes{fstype!=\"tmpfs\", mountpoint!~\"/run.*\"})\n) / sum(node_filesystem_size_bytes{fstype!=\"tmpfs\", mountpoint!~\"/run.*\"})\n",
     "legendFormat": "Utilisé"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation mémoire du cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "Libre"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) ",
     "legendFormat": "Utilisé"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SECTION 2 – Pods & Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Status des pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "count by(pod, phase) (\n  kube_pod_status_phase\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redémarrages de pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(pod) (\n  increase(kube_pod_container_status_restarts_total{pod!=\"\"}[10m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mémoire utilisée par pod (en bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(pod) (\n  container_memory_usage_bytes{job=\"kubernetes-nodes-cadvisor\", pod!=\"\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage par pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_cpu_usage_seconds_total{job=\"kubernetes-nodes-cadvisor\", pod!=\"\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SECTION 3 – Services Spring Boot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statut des requêtes HTTP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) by (app)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nombre de requêtes HTTP par endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Durée moyenne des requêtes HTTP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum[5m]) / rate(http_server_requests_seconds_count[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disponibilité des endpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "expr": "up{job=\"kubernetes-pods\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SECTION 4 – Services spécifiques",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth / Payment / Logement :",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "up{app=~\"authentification|payment-service|ter-logement\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Eureka :",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"eureka-server\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Config Server :",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "up{app=\"config-server\"}\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gateway :",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{app=\"api-gateway\"}[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SECTION 5 – Prometheus lui-même",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Durée des scrapes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "avg_over_time(scrape_duration_seconds{job!=\"\"}[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Health des targets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "expr": "up{job=\"prometheus\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}