spring:
  application:
    name: microservice-gateway
  config:
    import: configserver:http://config-server.default.svc.cluster.local:9090

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 